-- =====================================================================
-- V2 — Seed a curated catalog of well-known US universities (~100), incl. UCLA / UC Berkeley
-- Idempotent: ON CONFLICT (slug) DO NOTHING — safe to re-run.
-- NOTE: This is a curated starter set for MVP. Production should bulk-import
-- from an authoritative source (e.g. IPEDS) via an admin pipeline.
-- =====================================================================
INSERT INTO universities (slug, name, short_name, city, region, country_code, timezone, status) VALUES
  ('mit','Massachusetts Institute of Technology','MIT','Cambridge','MA','US','America/New_York','ACTIVE'),
  ('harvard','Harvard University','Harvard','Cambridge','MA','US','America/New_York','ACTIVE'),
  ('stanford','Stanford University','Stanford','Stanford','CA','US','America/Los_Angeles','ACTIVE'),
  ('caltech','California Institute of Technology','Caltech','Pasadena','CA','US','America/Los_Angeles','ACTIVE'),
  ('princeton','Princeton University','Princeton','Princeton','NJ','US','America/New_York','ACTIVE'),
  ('yale','Yale University','Yale','New Haven','CT','US','America/New_York','ACTIVE'),
  ('columbia','Columbia University','Columbia','New York','NY','US','America/New_York','ACTIVE'),
  ('uchicago','University of Chicago','UChicago','Chicago','IL','US','America/Chicago','ACTIVE'),
  ('penn','University of Pennsylvania','Penn','Philadelphia','PA','US','America/New_York','ACTIVE'),
  ('cornell','Cornell University','Cornell','Ithaca','NY','US','America/New_York','ACTIVE'),
  ('brown','Brown University','Brown','Providence','RI','US','America/New_York','ACTIVE'),
  ('dartmouth','Dartmouth College','Dartmouth','Hanover','NH','US','America/New_York','ACTIVE'),
  ('duke','Duke University','Duke','Durham','NC','US','America/New_York','ACTIVE'),
  ('johns-hopkins','Johns Hopkins University','Johns Hopkins','Baltimore','MD','US','America/New_York','ACTIVE'),
  ('northwestern','Northwestern University','Northwestern','Evanston','IL','US','America/Chicago','ACTIVE'),
  ('vanderbilt','Vanderbilt University','Vanderbilt','Nashville','TN','US','America/Chicago','ACTIVE'),
  ('rice','Rice University','Rice','Houston','TX','US','America/Chicago','ACTIVE'),
  ('washu','Washington University in St. Louis','WashU','St. Louis','MO','US','America/Chicago','ACTIVE'),
  ('notre-dame','University of Notre Dame','Notre Dame','Notre Dame','IN','US','America/Indiana/Indianapolis','ACTIVE'),
  ('emory','Emory University','Emory','Atlanta','GA','US','America/New_York','ACTIVE'),
  ('georgetown','Georgetown University','Georgetown','Washington','DC','US','America/New_York','ACTIVE'),
  ('cmu','Carnegie Mellon University','CMU','Pittsburgh','PA','US','America/New_York','ACTIVE'),
  ('usc','University of Southern California','USC','Los Angeles','CA','US','America/Los_Angeles','ACTIVE'),
  ('nyu','New York University','NYU','New York','NY','US','America/New_York','ACTIVE'),
  ('tufts','Tufts University','Tufts','Medford','MA','US','America/New_York','ACTIVE'),
  ('michigan','University of Michigan','Michigan','Ann Arbor','MI','US','America/New_York','ACTIVE'),
  ('ucla','University of California, Los Angeles','UCLA','Los Angeles','CA','US','America/Los_Angeles','ACTIVE'),
  ('uc-berkeley','University of California, Berkeley','UC Berkeley','Berkeley','CA','US','America/Los_Angeles','ACTIVE'),
  ('uc-san-diego','University of California, San Diego','UC San Diego','La Jolla','CA','US','America/Los_Angeles','ACTIVE'),
  ('uc-davis','University of California, Davis','UC Davis','Davis','CA','US','America/Los_Angeles','ACTIVE'),
  ('uc-irvine','University of California, Irvine','UC Irvine','Irvine','CA','US','America/Los_Angeles','ACTIVE'),
  ('uc-santa-barbara','University of California, Santa Barbara','UC Santa Barbara','Santa Barbara','CA','US','America/Los_Angeles','ACTIVE'),
  ('uva','University of Virginia','UVA','Charlottesville','VA','US','America/New_York','ACTIVE'),
  ('unc','University of North Carolina at Chapel Hill','UNC','Chapel Hill','NC','US','America/New_York','ACTIVE'),
  ('uf','University of Florida','UF','Gainesville','FL','US','America/New_York','ACTIVE'),
  ('ut-austin','University of Texas at Austin','UT Austin','Austin','TX','US','America/Chicago','ACTIVE'),
  ('uw-madison','University of Wisconsin-Madison','UW-Madison','Madison','WI','US','America/Chicago','ACTIVE'),
  ('uiuc','University of Illinois Urbana-Champaign','UIUC','Champaign','IL','US','America/Chicago','ACTIVE'),
  ('uw','University of Washington','UW','Seattle','WA','US','America/Los_Angeles','ACTIVE'),
  ('georgia-tech','Georgia Institute of Technology','Georgia Tech','Atlanta','GA','US','America/New_York','ACTIVE'),
  ('uga','University of Georgia','UGA','Athens','GA','US','America/New_York','ACTIVE'),
  ('ohio-state','Ohio State University','Ohio State','Columbus','OH','US','America/New_York','ACTIVE'),
  ('penn-state','Pennsylvania State University','Penn State','University Park','PA','US','America/New_York','ACTIVE'),
  ('purdue','Purdue University','Purdue','West Lafayette','IN','US','America/Indiana/Indianapolis','ACTIVE'),
  ('umd','University of Maryland, College Park','UMD','College Park','MD','US','America/New_York','ACTIVE'),
  ('bu','Boston University','BU','Boston','MA','US','America/New_York','ACTIVE'),
  ('bc','Boston College','BC','Chestnut Hill','MA','US','America/New_York','ACTIVE'),
  ('northeastern','Northeastern University','Northeastern','Boston','MA','US','America/New_York','ACTIVE'),
  ('rochester','University of Rochester','Rochester','Rochester','NY','US','America/New_York','ACTIVE'),
  ('case-western','Case Western Reserve University','Case Western','Cleveland','OH','US','America/New_York','ACTIVE'),
  ('miami','University of Miami','Miami','Coral Gables','FL','US','America/New_York','ACTIVE'),
  ('wake-forest','Wake Forest University','Wake Forest','Winston-Salem','NC','US','America/New_York','ACTIVE'),
  ('brandeis','Brandeis University','Brandeis','Waltham','MA','US','America/New_York','ACTIVE'),
  ('william-mary','College of William & Mary','William & Mary','Williamsburg','VA','US','America/New_York','ACTIVE'),
  ('minnesota','University of Minnesota','Minnesota','Minneapolis','MN','US','America/Chicago','ACTIVE'),
  ('michigan-state','Michigan State University','Michigan State','East Lansing','MI','US','America/New_York','ACTIVE'),
  ('indiana','Indiana University Bloomington','Indiana','Bloomington','IN','US','America/Indiana/Indianapolis','ACTIVE'),
  ('texas-a-m','Texas A&M University','Texas A&M','College Station','TX','US','America/Chicago','ACTIVE'),
  ('arizona','University of Arizona','Arizona','Tucson','AZ','US','America/Phoenix','ACTIVE'),
  ('asu','Arizona State University','ASU','Tempe','AZ','US','America/Phoenix','ACTIVE'),
  ('cu-boulder','University of Colorado Boulder','CU Boulder','Boulder','CO','US','America/Denver','ACTIVE'),
  ('utah','University of Utah','Utah','Salt Lake City','UT','US','America/Denver','ACTIVE'),
  ('oregon','University of Oregon','Oregon','Eugene','OR','US','America/Los_Angeles','ACTIVE'),
  ('pitt','University of Pittsburgh','Pitt','Pittsburgh','PA','US','America/New_York','ACTIVE'),
  ('rutgers','Rutgers University','Rutgers','New Brunswick','NJ','US','America/New_York','ACTIVE'),
  ('uconn','University of Connecticut','UConn','Storrs','CT','US','America/New_York','ACTIVE'),
  ('umass-amherst','University of Massachusetts Amherst','UMass Amherst','Amherst','MA','US','America/New_York','ACTIVE'),
  ('syracuse','Syracuse University','Syracuse','Syracuse','NY','US','America/New_York','ACTIVE'),
  ('fsu','Florida State University','FSU','Tallahassee','FL','US','America/New_York','ACTIVE'),
  ('iowa','University of Iowa','Iowa','Iowa City','IA','US','America/Chicago','ACTIVE'),
  ('ku','University of Kansas','KU','Lawrence','KS','US','America/New_York','ACTIVE'),
  ('nebraska','University of Nebraska-Lincoln','Nebraska','Lincoln','NE','US','America/Chicago','ACTIVE'),
  ('mizzou','University of Missouri','Mizzou','Columbia','MO','US','America/Chicago','ACTIVE'),
  ('tennessee','University of Tennessee','Tennessee','Knoxville','TN','US','America/Chicago','ACTIVE'),
  ('alabama','University of Alabama','Alabama','Tuscaloosa','AL','US','America/Chicago','ACTIVE'),
  ('auburn','Auburn University','Auburn','Auburn','AL','US','America/Chicago','ACTIVE'),
  ('lsu','Louisiana State University','LSU','Baton Rouge','LA','US','America/Chicago','ACTIVE'),
  ('oklahoma','University of Oklahoma','Oklahoma','Norman','OK','US','America/Chicago','ACTIVE'),
  ('baylor','Baylor University','Baylor','Waco','TX','US','America/Chicago','ACTIVE'),
  ('smu','Southern Methodist University','SMU','Dallas','TX','US','America/Chicago','ACTIVE'),
  ('tcu','Texas Christian University','TCU','Fort Worth','TX','US','America/Chicago','ACTIVE'),
  ('houston','University of Houston','Houston','Houston','TX','US','America/Chicago','ACTIVE'),
  ('clemson','Clemson University','Clemson','Clemson','SC','US','America/New_York','ACTIVE'),
  ('south-carolina','University of South Carolina','South Carolina','Columbia','SC','US','America/New_York','ACTIVE'),
  ('nc-state','North Carolina State University','NC State','Raleigh','NC','US','America/New_York','ACTIVE'),
  ('virginia-tech','Virginia Tech','Virginia Tech','Blacksburg','VA','US','America/New_York','ACTIVE'),
  ('kentucky','University of Kentucky','Kentucky','Lexington','KY','US','America/New_York','ACTIVE'),
  ('cincinnati','University of Cincinnati','Cincinnati','Cincinnati','OH','US','America/New_York','ACTIVE'),
  ('stony-brook','Stony Brook University','Stony Brook','Stony Brook','NY','US','America/New_York','ACTIVE'),
  ('ub','University at Buffalo','UB','Buffalo','NY','US','America/New_York','ACTIVE'),
  ('fordham','Fordham University','Fordham','New York','NY','US','America/New_York','ACTIVE'),
  ('gw','George Washington University','GW','Washington','DC','US','America/New_York','ACTIVE'),
  ('american','American University','American','Washington','DC','US','America/New_York','ACTIVE'),
  ('denver','University of Denver','Denver','Denver','CO','US','America/Denver','ACTIVE'),
  ('pepperdine','Pepperdine University','Pepperdine','Malibu','CA','US','America/Los_Angeles','ACTIVE'),
  ('santa-clara','Santa Clara University','Santa Clara','Santa Clara','CA','US','America/Los_Angeles','ACTIVE'),
  ('usd','University of San Diego','USD','San Diego','CA','US','America/Los_Angeles','ACTIVE'),
  ('villanova','Villanova University','Villanova','Villanova','PA','US','America/New_York','ACTIVE'),
  ('lehigh','Lehigh University','Lehigh','Bethlehem','PA','US','America/New_York','ACTIVE'),
  ('rpi','Rensselaer Polytechnic Institute','RPI','Troy','NY','US','America/New_York','ACTIVE'),
  ('wpi','Worcester Polytechnic Institute','WPI','Worcester','MA','US','America/New_York','ACTIVE'),
  ('hawaii','University of Hawaii at Manoa','Hawaii','Honolulu','HI','US','Pacific/Honolulu','ACTIVE')
ON CONFLICT (slug) DO NOTHING;
